name: "Create Build Properties"
description: "Create Build Properties"
inputs:
  build-properties:
    description: "build properties"
    required: false
    default: "build.properties"
  application-id:
    description: "application id"
    required: true
  compile-sdk:
    description: "compile sdk"
    required: true
  min-sdk:
    description: "compile sdk"
    required: true
  target-sdk:
    description: "compile sdk"
    required: true
  version-code:
    description: "version code"
    required: false
    default: "1"
  version-name:
    description: "version name"
    required: false
    default: "1.0.0"
runs:
  using: "composite"
  steps:
    - run: |
        echo applicationId=${{ inputs.application-id }} > ${{ inputs.build-properties }}
        echo compileSdk=${{ inputs.compile-sdk }} >> ${{ inputs.build-properties }}
        echo minSdk=${{ inputs.min-sdk }} >> ${{ inputs.build-properties }}
        echo targetSdk=${{ inputs.target-sdk }} >> ${{ inputs.build-properties }}
        echo versionCode=${{ inputs.version-code }} >> ${{ inputs.build-properties }}
        echo versionName=${{ inputs.version-name }} >> ${{ inputs.build-properties }}
      shell: bash